name: Denní kontrola práce do RSS

on:
  schedule:
    - cron: '0 6 * * *' # Spustí se každý den v 6:00 ráno UTC
  workflow_dispatch:

jobs:
  scrape_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repozitáře
      uses: actions/checkout@v4

    - name: Nastavení Pythonu
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalace knihoven
      run: |
        pip install requests beautifulsoup4 feedgen urllib3 apify-client

    - name: Run Python Scraper
      env:
        APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
      run: |
        python scraper.py

    - name: Uložení změn a push do repozitáře
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git add pracovni_nabidky.xml
        git commit -m "Aktualizace RSS feedu: $(date +'%Y-%m-%d')" || echo "Žádné nové změny"
        git push
